.MODEL SMALL 

                                     
                                     
; --- FOR PRINTING A STRING ---

PRINT_STRING MACRO STRING 
    MOV AH, 9
    LEA DX, STRING      
    INT 21H
ENDM
                                     
                               
 
; ---- CLEARING THE ENTIRE SCREEN ----

CLEAR_SCREEN MACRO
    MOV AH, 6
    MOV AL, 0
    MOV BH, 7
    MOV CX, 0
    MOV DX, 6223
    INT 10H
    
    MOV AH, 2
    MOV BH, 0
    MOV DH, 0
    MOV DL, 0
    INT 10H
    
ENDM
    

; ---- FOR PRINTING ANY PAGE TITLE ----

PAGE_TITLE MACRO TITLE
                 
    PRINT_STRING TITLE_BARS    
    
    NEW_LINE
                    
    PRINT_STRING SPACES
    
    PRINT_STRING TITLE 
    
    NEW_LINE
    
    PRINT_STRING TITLE_BARS       
    
    NEW_LINE

ENDM                           


                      
; ---- JUMPING TO A NEW LINE ----

NEW_LINE MACRO 
    
    ; LINE FEED 
    MOV AH, 2
    MOV DL, 10
    INT 21H
    
    ; CARRIAGE RETURN 
    MOV AH, 2
    MOV DL, 13
    INT 21H
ENDM                              


                      
; ---- FOR PRINTING ANYTHING OF BYTE LENGTH (SINGLE CHARACTER) ----

PRINT_BYTE MACRO SOMETHING 
    
    MOV AH,2
    MOV DL, SOMETHING 
    INT 21H

ENDM                                        

                                
 
; ---- FOR TAKING A LONG STRING AS INPUT ----

INPUT_LONG_STRING MACRO  BUFFER 
    LEA DX, BUFFER 
    MOV AH, 10
    INT 21H
ENDM
                           
                           
                           
; ---- FOR PRINTING ANYTHING OF WORD LENGTH ----

PRINT_DIGIT MACRO SOMETHING 
    
    MOV AX, SOMETHING
    ADD AL, 48
    MOV DL, AL 
    MOV AH, 2
    INT 21H

ENDM
                                    
                                    
                                    
; ----INPUT AN INT VAL ----

INPUT_INT MACRO  
        ;MOV DL, VAL
        MOV AH, 1
        INT 21H
ENDM

            
            
; ---- ERROR_INPUT (ALSO TAKES ANOTHER INPUT) ----

ERROR_INPUT MACRO    
    NEW_LINE
    PRINT_STRING SPACED_DASHES     
    
    NEW_LINE
    PRINT_STRING SPACES
    PRINT_STRING END_MARK       
    PRINT_STRING INVALID_INPUT
    PRINT_STRING END_MARK 
    NEW_LINE                           
                          
    PRINT_STRING SPACED_DASHES        
    NEW_LINE         
 
ENDM
                         
                        
   
; ---- LOGIN PAGE CREDENTIALS ----

LOGIN_SIGNUP_PAGE_CREDENTIALS MACRO           
    
        NEW_LINE
        NEW_LINE
        PRINT_STRING LOGIN_NOTICE
        NEW_LINE
        NEW_LINE 
        PRINT_STRING SIGNUP_NOTICE
        NEW_LINE
        NEW_LINE             
        NEW_LINE    
        
        MOV CX, 5
        INPUT_LOOP_BEGIN:
            PRINT_STRING    GIVE_INPUT
            PRINT_DIGIT CX                
            PRINT_STRING  MAX_ALLOWED_ATTEMPT
            INPUT_INT                  
            SUB AL, 48
            CMP AL, 1
            JE IS_1
            CMP AL, 2
            JE IS_2
            
            JMP ERROR_CALL

            IS_1:              
            MOV CX, 0
            CALL LOAD_LOGIN_BOX  
            JMP CHECKER_END
    
            IS_2:    
            MOV CX, 0
            CALL LOAD_SIGNUP_BOX     
            JMP CHECKER_END
            
            ERROR_CALL:
                ERROR_INPUT  
        
        LOOP   INPUT_LOOP_BEGIN       
        PRINT_STRING RESTART   
        
        
    
        CHECKER_END:   
        MOV CX, 0
        ENDM
                                              
                           
                           
; ---- LOGIN BOX CREDENTIALS ---- 

LOGIN_BOX_CREDENTIALS MACRO 
    ;LOCAL LOGIN_INPUT_LOOP_BEGIN, INPT_0, INPT_1, LOGIN_SUCCESSFUL,   LOGIN_ERROR_CALL       ,LOGIN_LIMIT_FINISHED , LOGIN_BOX_END   
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING EMAIL              
    INPUT_LONG_STRING EMAIL_BUFFER
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING PASSWORD              
    INPUT_LONG_STRING PASSWORD_BUFFER
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING SPACED_DASHES
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING COFIRM_BUTTON
    NEW_LINE 
    NEW_LINE 
    
    PRINT_STRING  GO_BACK_BUTTON
    NEW_LINE 
    NEW_LINE
                        
     PRINT_STRING SPACED_DASHES
    NEW_LINE
    NEW_LINE
    
    MOV BX , ITERATOR
     LOGIN_INPUT_LOOP_BEGIN:
        CMP BX, 0
        JE   LOGIN_LIMIT_FINISHED  
                 
        PRINT_STRING GIVE_INPUT 
        PRINT_DIGIT BX
        PRINT_STRING MAX_ALLOWED_ATTEMPT
        
        INPUT_INT        
        
        SUB AL, 48     
        
        CMP AL, 0        
        
        JE  INPT_0
        CMP AL, 1
        JE INPT_1
        
        JMP LOGIN_ERROR_CALL
        
        INPT_0:
         ;
        JMP ROOT_PAGE     
        
        
       INPT_1:            
        CALL CHECK_LOGIN_USER
        CMP USER_FOUND, 1
        JE LOGIN_SUCCESSFUL     
        
        
        NEW_LINE    
        NEW_LINE
        PRINT_STRING SPACED_DASHES
        NEW_LINE 
        PRINT_STRING LOGIN_FAILED 
        NEW_LINE 
        PRINT_STRING SPACED_DASHES
        NEW_LINE
        NEW_LINE              
        
         PRINT_STRING RESTART  
         JMP LOGIN_BOX_END
        
        DEC BX
        JMP LOGIN_INPUT_LOOP_BEGIN
        
        LOGIN_SUCCESSFUL:
            NEW_LINE                
            NEW_LINE   
            PRINT_STRING SPACED_DASHES  
            NEW_LINE          
            PRINT_STRING LOGIN_SUCCESS    
            NEW_LINE 
            PRINT_STRING SPACED_DASHES 
            NEW_LINE
            NEW_LINE
            MOV LOGGED_IN, 1
            CALL CHECK_BRACU_EMAIL
            MOV CURRENT_BRACU, AL
            JMP LOGIN_BOX_END
            
        ;JMP LOGIN_BOX_END
        
         LOGIN_ERROR_CALL:
            ERROR_INPUT          
            DEC BX
            JMP LOGIN_INPUT_LOOP_BEGIN
 

        LOGIN_LIMIT_FINISHED:
            PRINT_STRING RESTART   
            JMP ROOT_PAGE
         ;CALL LOAD_LOGIN_SIGNUP_PAGE  
    
        LOGIN_BOX_END:       
        
ENDM           



; ---- SIGN UP BOX CREDENTIALS ---- 

SIGNUP_BOX_CREDENTIALS MACRO              
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING EMAIL              
    INPUT_LONG_STRING EMAIL_BUFFER
    NEW_LINE
    NEW_LINE
    
    PRINT_STRING PASSWORD              
    INPUT_LONG_STRING PASSWORD_BUFFER
    NEW_LINE
    NEW_LINE     
    
    PRINT_STRING COFIRM_BUTTON
    NEW_LINE 
    NEW_LINE 
    
    PRINT_STRING  GO_BACK_BUTTON
    NEW_LINE 
    NEW_LINE            
    
     PRINT_STRING SPACED_DASHES
    NEW_LINE
    NEW_LINE
    
    MOV BX , ITERATOR
    SIGNUP_INPUT_LOOP_BEGIN:        
        CMP SIGN_UP_DONE, 1
        JNE NO_GO_BACK_ACTIVATED    
                NEW_LINE
                PRINT_STRING GIVE_INPUT_NO_BRACKS        
                INPUT_INT 
                SUB AL, 48
                CMP AL, 0
                JE  ROOT_PAGE
                DEC BX
                JMP SIGNUP_INPUT_LOOP_BEGIN
                
                
                
        NO_GO_BACK_ACTIVATED:
        CMP BX, 0
        JE   SIGNUP_LIMIT_FINISHED      
             
        PRINT_STRING GIVE_INPUT 
        PRINT_DIGIT BX
        PRINT_STRING MAX_ALLOWED_ATTEMPT
        
        INPUT_INT 
        SUB AL, 48
        CMP AL, 0
        JE  INPUT_0
        CMP AL, 1
        JE INPUT_1
        
        JMP SIGNUP_ERROR_CALL
        
        INPUT_0:
         ;CALL LOAD_LOGIN_SIGNUP_PAGE 
        JMP ROOT_PAGE     
        
        
        INPUT_1:
        MOV AH , 2                 
        CALL STORE_SIGNUP_USER
        NEW_LINE
        NEW_LINE 
        PRINT_STRING SPACED_DASHES    
            NEW_LINE 
    
        PRINT_STRING SIGNUP_SUCCESS
        NEW_LINE 
        PRINT_STRING SPACED_DASHES 
        NEW_LINE
        NEW_LINE
            
        MOV SIGN_UP_DONE, 1
        NEW_LINE
        
        ;JMP SIGNUP_BOX_END        
        
        PRINT_STRING GO_BACK_BUTTON
        NEW_LINE

        JMP  SIGNUP_INPUT_LOOP_BEGIN
        
        
        ;DEC BX           
        ;JMP SIGNUP_INPUT_LOOP_BEGIN
        ;JMP LOGIN_BOX_END
        
        SIGNUP_ERROR_CALL:
            ERROR_INPUT          
            DEC BX
            JMP SIGNUP_INPUT_LOOP_BEGIN
 

        SIGNUP_LIMIT_FINISHED:
            PRINT_STRING RESTART   
            JMP ROOT_PAGE
         ;CALL LOAD_LOGIN_SIGNUP_PAGE  
    
        SIGNUP_BOX_END:       
        
ENDM           
    
 
ENDM     

.STACK 100H

.DATA

; declare variables here       
  
FALSE DB 0
TRUE DB 1        
LOGGED_IN DB 0              
LOGGED_USER_INDEX DB 0
CURRENT_BRACU DB 0
           

TITLE_BARS DB "========================================$"            
SPACED_DASHES DB "- - - - - - - - - - - - - - - - - - - - -$"
END_MARK DB "|$"
GIVE_INPUT_NO_BRACKS DB " GIVE  INPUT : $"

SPACES DB "          $"              
GIVE_INPUT DB " GIVE INPUT ($"            
MAX_ALLOWED_ATTEMPT DB " ATTEMPTS REMAINING TO PRESS RIGHT KEY ): $"     

RESTART DB " REFRESH THE SITE $"

INVALID_INPUT DB "  INVALID INPUT  $"
GIVE_INPUT_AGAIN DB " GIVE INPUT AGAIN $"      

ITERATOR DW 5  

; ---- LOGIN SIGNUP PAGE VARIABLES ----

LOGIN_SIGNUP_PAGE_TITLE DB "LOGIN OR SIGN UP $"                     
LOGIN_NOTICE DB ">>>>    PRESS 1 TO LOGIN $"
SIGNUP_NOTICE DB ">>>>    PRESS 2 TO SIGN UP $"     
LOGIN_SIGNUP_OPTIONS_APPEAR DB ?                     
LOGIN_PAGE_TITLE DB " LOG  IN $"
SIGNUP_PAGE_TITLE DB " SIGN UP $"          


; ---- LOGIN, SIGNUP BOX VARIABLES ----                          


EMAIL DB ">>>> EMAIL (Max 100 Characters Allowed) : $ "
EMAIL_MAX_ALLOWED_SIZE DB 100 

EMAIL_BUFFER DB 100 
             DB ? 
             DB 100 DUP(?)

PASSWORD DB ">>>> PASSWORD (Max 100 Characters Allowed) : $ "
PASSWORD_MAX_ALLOWED_SIZE DB 100                                 
             
PASSWORD_BUFFER DB 100 
                DB ? 
                DB 100 DUP(?)                  
 
BRACU_DOMAIN DB "@g.bracu.ac.bd"
 
COFIRM_BUTTON DB ">>>> PRESS 1 TO CONFIRM $"
GO_BACK_BUTTON DB ">>>> PRESS 0 TO CANCEL AND GO BACK $"

USER_FOUND DB 0  
SIGN_UP_DONE DB 0

LOGIN_SUCCESS DB " LOGIN SUCCESSFUL $"    
LOGIN_FAILED DB " INVALID EMAIL OR PASSWORD $"

SIGNUP_SUCCESS DB " SIGN UP SUCCESSFUL $"
                                                 

; ---- STORAGES ----
TOTAL_USERS DB 0
EMAIL_STORAGE DB 100 DUP(100 DUP(?))
PASSWORD_STORAGE DB 100 DUP(100 DUP(?))     
IS_BRACU DB 100 DUP(0)


; ---------------- MEMBER 3 DATA ----------------

MAX_CART_ITEMS DB 5
CART_COUNT DB 0
CART_BOOK_IDS DB 5 DUP(0)
CART_QUANTITY DB 5 DUP(0)

TEMP_BOOK_ID DB 0
TEMP_QUANTITY DB 0
TEMP_BOOK_INDEX DB 0
TEMP_CART_INDEX DB 0
CART_FOUND DB 0
BOOK_FOUND DB 0

TOTAL_ITEMS DB 0
SUBTOTAL DW 0
DISCOUNT DW 0
FINAL_TOTAL DW 0

; Temporary book data
; Replace these arrays later with the arrays from the Updating Stock member.
TOTAL_BOOKS DB 5
BOOK_IDS DB 1,2,3,4,5
BOOK_PRICES DB 25,35,45,30,50
BOOK_STOCK DB 5,4,6,3,5

BOOK1_TITLE DB "The Alchemist$"
BOOK2_TITLE DB "Atomic Habits$"
BOOK3_TITLE DB "The Hobbit$"
BOOK4_TITLE DB "1984$"
BOOK5_TITLE DB "Pride and Prejudice$"

BUYER_MENU_TITLE DB " BUYER MENU $"
CART_MENU_TITLE DB " SHOPPING CART $"
BILL_TITLE DB " AUTOMATIC BILL $"

BUYER_MENU_1 DB ">>>> PRESS 1 FOR SHOPPING CART $"
BUYER_MENU_2 DB ">>>> PRESS 2 FOR AUTOMATIC BILL $"
BUYER_MENU_3 DB ">>>> PRESS 3 TO VIEW BOOKS $"
BUYER_MENU_4 DB ">>>> PRESS 4 TO LOGOUT $"

CART_MENU_1 DB ">>>> PRESS 1 TO ADD BOOK $"
CART_MENU_2 DB ">>>> PRESS 2 TO REMOVE BOOK $"
CART_MENU_3 DB ">>>> PRESS 3 TO CHANGE QUANTITY $"
CART_MENU_4 DB ">>>> PRESS 4 TO VIEW CART $"
CART_MENU_5 DB ">>>> PRESS 5 TO GO BACK $"

BOOK_ID_INPUT DB ">>>> ENTER BOOK ID: $"
BOOK_ID_ONE DB "1 $"
BOOK_ID_TWO DB "2 $"
BOOK_ID_THREE DB "3 $"
BOOK_ID_FOUR DB "4 $"
BOOK_ID_FIVE DB "5 $"
BOOK_STOCK_MESSAGE DB " STOCK: $"
QUANTITY_INPUT DB ">>>> ENTER QUANTITY (1-9): $"
NEW_QUANTITY_INPUT DB ">>>> ENTER NEW QUANTITY (1-9): $"

BOOK_ADDED DB " BOOK ADDED TO CART $"
BOOK_REMOVED DB " BOOK REMOVED FROM CART $"
QUANTITY_CHANGED DB " QUANTITY UPDATED $"
CART_EMPTY DB " CART IS EMPTY $"
CART_FULL DB " CART IS FULL $"
INVALID_BOOK DB " INVALID BOOK ID $"
INVALID_QUANTITY DB " INVALID QUANTITY $"
OUT_OF_STOCK DB " BOOK IS OUT OF STOCK $"
NOT_ENOUGH_STOCK DB " NOT ENOUGH STOCK AVAILABLE $"
BOOK_NOT_IN_CART DB " BOOK IS NOT IN CART $"

CART_BOOK DB " BOOK ID: $"
CART_TITLE DB " TITLE: $"
CART_QTY DB " QUANTITY: $"
CART_PRICE DB " PRICE: $"

BILL_SUBTOTAL DB " SUBTOTAL: $"
BILL_DISCOUNT DB " DISCOUNT: $"
BILL_FINAL DB " FINAL TOTAL: $"
TOTAL_ITEM_MESSAGE DB " TOTAL ITEMS: $"
DISCOUNT_APPLIED DB " 20 PERCENT BRACU STUDENT DISCOUNT APPLIED $"
NO_DISCOUNT DB " NO DISCOUNT APPLIED $"
BILL_READY DB " BILL GENERATED SUCCESSFULLY $"
PRESS_BACK DB " PRESS 0 TO GO BACK $"




.CODE
MAIN PROC

; initialize DS

MOV AX,@DATA
MOV DS,AX
 
; enter your code here   
ROOT_PAGE:
CALL PAGE_LOADER
JMP ROOT_PAGE


 



 

;exit to DOS
               
MOV AX,4C00H
INT 21H

MAIN ENDP                   

PAGE_LOADER PROC
    MOV AL, TRUE
    CMP LOGGED_IN, AL
    JE WEBSITE
    MOV LOGIN_SIGNUP_OPTIONS_APPEAR, AL
    CALL LOAD_LOGIN_SIGNUP_PAGE
    MOV AL, TRUE
    CMP LOGGED_IN, AL
    JE WEBSITE
    RET

    WEBSITE:
    CALL BUYER_PAGE
    RET
PAGE_LOADER ENDP

LOAD_LOGIN_SIGNUP_PAGE PROC
    CLEAR_SCREEN
    PAGE_TITLE LOGIN_SIGNUP_PAGE_TITLE       
    LOGIN_SIGNUP_PAGE_CREDENTIALS     
    ;CLEAR_SCREEN
    RET
LOAD_LOGIN_SIGNUP_PAGE ENDP  


 
LOAD_LOGIN_BOX PROC
    CLEAR_SCREEN   
    
    ;LEA SI, 
    PAGE_TITLE LOGIN_PAGE_TITLE               
    LOGIN_BOX_CREDENTIALS
    RET
LOAD_LOGIN_BOX ENDP   



LOAD_SIGNUP_BOX PROC
    CLEAR_SCREEN   
    
    ;LEA SI, 
    PAGE_TITLE SIGNUP_PAGE_TITLE               
    SIGNUP_BOX_CREDENTIALS
    RET
LOAD_SIGNUP_BOX ENDP        



CHECK_BRACU_EMAIL PROC
    MOV AL, 0
    MOV BL, EMAIL_BUFFER + 1
    CMP BL, 14
    JB NOT_BRACU

    LEA SI, EMAIL_BUFFER
    INC SI
    INC SI

    MOV AL, EMAIL_BUFFER + 1
    SUB AL, 14
    MOV AH, 0
    ADD SI, AX

    LEA DI, BRACU_DOMAIN
    MOV CX, 14

CHECK_DOMAIN:
    MOV AL, [SI]
    CMP AL, [DI]
    JNE NOT_BRACU

    INC SI
    INC DI
    LOOP CHECK_DOMAIN

    MOV AL, 1
    RET

NOT_BRACU:
    MOV AL, 0
    RET
CHECK_BRACU_EMAIL ENDP



STORE_SIGNUP_USER PROC
    
    ; TOTAL NUMBER OF USERS
    MOV AL, TOTAL_USERS
    MOV AH, 0
     
    MOV BL, 100
    MUL BL
 
    MOV DI, AX
    
    ; STORING EMAIL
    
    LEA SI, EMAIL_BUFFER
    INC SI
    
    MOV CL, EMAIL_BUFFER + 1
    MOV CH, 0
    
    STORE_EMAIL:
    CMP CX, 0
    JE EMAIL_DONE
    
    MOV AL, [SI]
    MOV EMAIL_STORAGE[DI], AL
    
    INC SI
    INC DI
    
    DEC CX
    JMP STORE_EMAIL
    
    EMAIL_DONE:
    
    MOV AL, TOTAL_USERS
    MOV AH, 0
    
    MOV BL, 100
    MUL BL
    
    MOV DI, AX
    
    ; STORING PASSWORD 
    
    LEA SI, PASSWORD_BUFFER
    
    INC SI
    
    MOV CL, PASSWORD_BUFFER + 1
    MOV CH, 0
    
    STORE_PASSWORD:
    CMP CX, 0
    JE PASSWORD_DONE
    
    MOV AL, [SI]
    MOV PASSWORD_STORAGE[DI], AL
    
    INC SI
    INC DI
    
    DEC CX
    
    JMP STORE_PASSWORD
    
    PASSWORD_DONE:
    CALL CHECK_BRACU_EMAIL
    
    MOV BL, TOTAL_USERS
    MOV BH, 0
    
    MOV IS_BRACU[BX], AL
    
    ;ADDING NEW USER
    
    INC TOTAL_USERS
 
    
    RET
STORE_SIGNUP_USER ENDP          



CHECK_LOGIN_USER  PROC                
    MOV USER_FOUND ,0
    MOV BL, 0
    MOV BH, 0
    
    CHECK_USER_LOOP:
        ; CHECKING IF ANY USER AVAILABLE
        CMP BL, TOTAL_USERS
        JE LOGIN_NOT_FOUND
        
        ; FINDING STORAGE POSITION
        
        MOV AL,BL
        MOV AH, 0
        
        MOV DL, 100
        MUL DL
        
        MOV DI, AX
        
        ; CHECKING EMAIL
        
        LEA SI, EMAIL_BUFFER
        INC SI
        
        MOV CL, EMAIL_BUFFER + 1
        
        MOV CH, 0
        
     CHECK_EMAIL:
        CMP CX, 0
        JE EMAIL_CHECK_DONE
        
        MOV AL, [SI]
        CMP AL, EMAIL_STORAGE[DI]
        JNE NEXT_USER
        
        INC SI
        INC DI
        
        DEC CX
        JMP CHECK_EMAIL
        
     EMAIL_CHECK_DONE:
        ; FINDING PASSWORD AND STORAGE POSITION
        
        MOV AL, BL
        MOV AH, 0
        
        MOV DL, 100
        MUL DL
        
        MOV DI, AX
        
        ; CHEKING PASSWORD 
        
        LEA SI, PASSWORD_BUFFER
        INC SI
        
        MOV CL,PASSWORD_BUFFER + 1
        MOV CH, 0
        
     CHECK_PASSWORD:
        CMP CX, 0
        JE LOGIN_FOUND          
        
        MOV AL, [SI]
        CMP AL, PASSWORD_STORAGE[DI]
        JNE NEXT_USER
        
        INC SI
        INC DI
        
        DEC  CX
        
        JMP CHECK_PASSWORD
        
     LOGIN_FOUND:
        MOV USER_FOUND ,1
        MOV LOGGED_USER_INDEX, BL
        RET
        
     NEXT_USER:
        INC BL
        JMP CHECK_USER_LOOP
        
     LOGIN_NOT_FOUND:
        MOV USER_FOUND, 0  
        
    
    RET
CHECK_LOGIN_USER ENDP



; ---------------- BUYER MENU ----------------

BUYER_PAGE PROC

BUYER_MENU:
    CLEAR_SCREEN
    PAGE_TITLE BUYER_MENU_TITLE

    PRINT_STRING BUYER_MENU_1
    NEW_LINE
    NEW_LINE

    PRINT_STRING BUYER_MENU_2
    NEW_LINE
    NEW_LINE

    PRINT_STRING BUYER_MENU_3
    NEW_LINE
    NEW_LINE

    PRINT_STRING BUYER_MENU_4
    NEW_LINE
    NEW_LINE

    PRINT_STRING SPACED_DASHES
    NEW_LINE
    PRINT_STRING GIVE_INPUT_NO_BRACKS
    INPUT_INT
    SUB AL,48

    CMP AL,1
    JE BUYER_CART

    CMP AL,2
    JE BUYER_BILL

    CMP AL,3
    JE BUYER_BOOKS

    CMP AL,4
    JE BUYER_LOGOUT

BUYER_INVALID_INPUT:
    ERROR_INPUT
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    PRINT_STRING GIVE_INPUT_NO_BRACKS
    INPUT_INT
    SUB AL,48

    CMP AL,1
    JE BUYER_CART
    CMP AL,2
    JE BUYER_BILL
    CMP AL,3
    JE BUYER_BOOKS
    CMP AL,4
    JE BUYER_LOGOUT
    JMP BUYER_INVALID_INPUT

BUYER_BOOKS:
    CALL VIEW_BOOKS
    JMP BUYER_MENU

BUYER_CART:
    CALL SHOPPING_CART
    JMP BUYER_MENU

BUYER_BILL:
    CALL GENERATE_BILL
    JMP BUYER_MENU

BUYER_LOGOUT:
    MOV LOGGED_IN,0
    MOV CURRENT_BRACU,0
    MOV CART_COUNT,0
    RET

BUYER_PAGE ENDP


; ---------------- VIEW AVAILABLE BOOKS ----------------
; Shows the available books, prices and stock.
; This allows the buyer to find a Book ID before adding it to the cart.

VIEW_BOOKS PROC

    CLEAR_SCREEN
    PAGE_TITLE BUYER_MENU_TITLE

    MOV SI,0

VIEW_BOOKS_LOOP:
    MOV AX,0
    MOV AL,TOTAL_BOOKS
    CMP SI,AX
    JAE VIEW_BOOKS_DONE

    PRINT_STRING SPACED_DASHES
    NEW_LINE

    PRINT_STRING CART_BOOK
    MOV AL,BOOK_IDS[SI]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING CART_PRICE
    MOV AL,BOOK_PRICES[SI]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING BOOK_STOCK_MESSAGE
    MOV AL,BOOK_STOCK[SI]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    INC SI
    JMP VIEW_BOOKS_LOOP

VIEW_BOOKS_DONE:
    NEW_LINE
    CALL WAIT_FOR_ZERO
    RET

VIEW_BOOKS ENDP


; ---------------- SHOPPING CART MENU ----------------

SHOPPING_CART PROC

CART_MENU:
    CLEAR_SCREEN
    PAGE_TITLE CART_MENU_TITLE

    PRINT_STRING CART_MENU_1
    NEW_LINE
    NEW_LINE

    PRINT_STRING CART_MENU_2
    NEW_LINE
    NEW_LINE

    PRINT_STRING CART_MENU_3
    NEW_LINE
    NEW_LINE

    PRINT_STRING CART_MENU_4
    NEW_LINE
    NEW_LINE

    PRINT_STRING CART_MENU_5
    NEW_LINE
    NEW_LINE

    PRINT_STRING SPACED_DASHES
    NEW_LINE
    PRINT_STRING GIVE_INPUT_NO_BRACKS
    INPUT_INT
    SUB AL,48

    CMP AL,1
    JE CART_ADD

    CMP AL,2
    JE CART_REMOVE

    CMP AL,3
    JE CART_CHANGE

    CMP AL,4
    JE CART_VIEW

    CMP AL,5
    JE CART_BACK

CART_INVALID_INPUT:
    ERROR_INPUT
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    PRINT_STRING GIVE_INPUT_NO_BRACKS
    INPUT_INT
    SUB AL,48

    CMP AL,1
    JE CART_ADD
    CMP AL,2
    JE CART_REMOVE
    CMP AL,3
    JE CART_CHANGE
    CMP AL,4
    JE CART_VIEW
    CMP AL,5
    JE CART_BACK
    JMP CART_INVALID_INPUT

CART_ADD:
    CALL ADD_TO_CART
    JMP CART_MENU

CART_REMOVE:
    CALL REMOVE_FROM_CART
    JMP CART_MENU

CART_CHANGE:
    CALL CHANGE_CART_QUANTITY
    JMP CART_MENU

CART_VIEW:
    CALL VIEW_CART
    JMP CART_MENU

CART_BACK:
    RET

SHOPPING_CART ENDP


; ---------------- FIND BOOK ----------------
; Input: AL = Book ID
; Output: BX = book index, BOOK_FOUND = 1 if found

FIND_BOOK_INDEX PROC

    MOV BOOK_FOUND,0
    MOV DL,AL
    MOV SI,0

FIND_BOOK_LOOP:
    MOV AX,0
    MOV AL,TOTAL_BOOKS
    CMP SI,AX
    JAE FIND_BOOK_END

    MOV AL,DL
    CMP AL,BOOK_IDS[SI]
    JE FIND_BOOK_FOUND

    INC SI
    JMP FIND_BOOK_LOOP

FIND_BOOK_FOUND:
    MOV BX,SI
    MOV BOOK_FOUND,1

FIND_BOOK_END:
    RET

FIND_BOOK_INDEX ENDP


; ---------------- FIND CART ITEM ----------------
; Input: AL = Book ID
; Output: BX = cart index, CART_FOUND = 1 if found

FIND_CART_ITEM PROC

    MOV CART_FOUND,0
    MOV DL,AL
    MOV SI,0

FIND_CART_LOOP:
    MOV AX,0
    MOV AL,CART_COUNT
    CMP SI,AX
    JAE FIND_CART_END

    MOV AL,DL
    CMP AL,CART_BOOK_IDS[SI]
    JE FIND_CART_FOUND

    INC SI
    JMP FIND_CART_LOOP

FIND_CART_FOUND:
    MOV BX,SI
    MOV CART_FOUND,1

FIND_CART_END:
    RET

FIND_CART_ITEM ENDP


; ---------------- ADD BOOK TO CART ----------------

ADD_TO_CART PROC

    CLEAR_SCREEN
    PAGE_TITLE CART_MENU_TITLE

ADD_BOOK_INPUT:
    PRINT_STRING BOOK_ID_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_BOOK_ID,AL
    NEW_LINE

    MOV AL,TEMP_BOOK_ID
    CALL FIND_BOOK_INDEX

    CMP BOOK_FOUND,1
    JE ADD_BOOK_ID_OK

    PRINT_STRING INVALID_BOOK
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP ADD_BOOK_INPUT

ADD_BOOK_ID_OK:
    MOV TEMP_BOOK_INDEX,BL

    MOV BL,TEMP_BOOK_INDEX
    MOV BH,0

    MOV AL,BOOK_STOCK[BX]
    CMP AL,0
    JE ADD_OUT_OF_STOCK

    MOV AL,TEMP_BOOK_ID
    CALL FIND_CART_ITEM

    CMP CART_FOUND,1
    JE ADD_EXISTING_BOOK

    MOV AL,CART_COUNT
    CMP AL,MAX_CART_ITEMS
    JAE CART_IS_FULL

    MOV AL,CART_COUNT
    MOV AH,0
    MOV SI,AX

    MOV AL,TEMP_BOOK_ID
    MOV CART_BOOK_IDS[SI],AL

ADD_NEW_QUANTITY:
    PRINT_STRING QUANTITY_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_QUANTITY,AL
    NEW_LINE

    MOV AL,TEMP_QUANTITY
    CMP AL,1
    JB ADD_INVALID_NEW_QUANTITY
    CMP AL,9
    JA ADD_INVALID_NEW_QUANTITY
    JMP ADD_NEW_QTY_OK

ADD_INVALID_NEW_QUANTITY:
    PRINT_STRING INVALID_QUANTITY
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP ADD_NEW_QUANTITY

ADD_NEW_QTY_OK:

    MOV BL,TEMP_BOOK_INDEX
    MOV BH,0

    CMP AL,BOOK_STOCK[BX]
    JA ADD_NOT_ENOUGH_STOCK

    MOV AL,TEMP_QUANTITY
    MOV CART_QUANTITY[SI],AL

    INC CART_COUNT

    PRINT_STRING BOOK_ADDED
    NEW_LINE
    JMP ADD_CART_DONE

ADD_EXISTING_BOOK:

    MOV TEMP_CART_INDEX,BL

ADD_EXISTING_QUANTITY:
    PRINT_STRING QUANTITY_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_QUANTITY,AL
    NEW_LINE

    MOV AL,TEMP_QUANTITY
    CMP AL,1
    JB ADD_INVALID_EXISTING_QUANTITY
    CMP AL,9
    JA ADD_INVALID_EXISTING_QUANTITY
    JMP ADD_EXISTING_QTY_OK

ADD_INVALID_EXISTING_QUANTITY:
    PRINT_STRING INVALID_QUANTITY
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP ADD_EXISTING_QUANTITY

ADD_EXISTING_QTY_OK:

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX

    MOV AL,CART_QUANTITY[SI]
    MOV BL,TEMP_QUANTITY
    ADD AL,BL
    MOV TEMP_QUANTITY,AL

    MOV BL,TEMP_BOOK_INDEX
    MOV BH,0

    CMP AL,BOOK_STOCK[BX]
    JA ADD_NOT_ENOUGH_STOCK

    MOV AL,TEMP_QUANTITY
    MOV CART_QUANTITY[SI],AL

    PRINT_STRING BOOK_ADDED
    NEW_LINE
    JMP ADD_CART_DONE

ADD_OUT_OF_STOCK:
    PRINT_STRING OUT_OF_STOCK
    NEW_LINE
    JMP ADD_CART_DONE

ADD_NOT_ENOUGH_STOCK:
    PRINT_STRING NOT_ENOUGH_STOCK
    NEW_LINE
    JMP ADD_CART_DONE

CART_IS_FULL:
    PRINT_STRING CART_FULL
    NEW_LINE

ADD_CART_DONE:
ADD_CART_BACK:
    PRINT_STRING PRESS_BACK
    NEW_LINE
    INPUT_INT
    CMP AL,'0'
    JE ADD_CART_RETURN  
     
    NEW_LINE
    PRINT_STRING INVALID_INPUT
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP ADD_CART_BACK

ADD_CART_RETURN:
    RET

ADD_TO_CART ENDP


; ---------------- REMOVE BOOK FROM CART ----------------

REMOVE_FROM_CART PROC

    CLEAR_SCREEN
    PAGE_TITLE CART_MENU_TITLE

    CMP CART_COUNT,0
    JE REMOVE_EMPTY

    PRINT_STRING BOOK_ID_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_BOOK_ID,AL
    NEW_LINE

    MOV AL,TEMP_BOOK_ID
    CALL FIND_CART_ITEM

    CMP CART_FOUND,1
    JNE REMOVE_NOT_FOUND

    MOV TEMP_CART_INDEX,BL

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX

    MOV DI,SI
    INC DI

REMOVE_SHIFT_LOOP:
    MOV AX,0
    MOV AL,CART_COUNT
    CMP DI,AX
    JAE REMOVE_SHIFT_DONE

    MOV AL,CART_BOOK_IDS[DI]
    MOV CART_BOOK_IDS[SI],AL

    MOV AL,CART_QUANTITY[DI]
    MOV CART_QUANTITY[SI],AL

    INC SI
    INC DI
    JMP REMOVE_SHIFT_LOOP

REMOVE_SHIFT_DONE:
    DEC CART_COUNT

    PRINT_STRING BOOK_REMOVED
    NEW_LINE
    JMP REMOVE_DONE

REMOVE_EMPTY:
    PRINT_STRING CART_EMPTY
    NEW_LINE
    JMP REMOVE_DONE

REMOVE_NOT_FOUND:
    PRINT_STRING BOOK_NOT_IN_CART
    NEW_LINE

REMOVE_DONE:
    CALL WAIT_FOR_ZERO
    RET

REMOVE_FROM_CART ENDP


; ---------------- CHANGE CART QUANTITY ----------------

CHANGE_CART_QUANTITY PROC

    CLEAR_SCREEN
    PAGE_TITLE CART_MENU_TITLE

    CMP CART_COUNT,0
    JE CHANGE_EMPTY

    PRINT_STRING BOOK_ID_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_BOOK_ID,AL
    NEW_LINE

    MOV AL,TEMP_BOOK_ID
    CALL FIND_CART_ITEM

    CMP CART_FOUND,1
    JNE CHANGE_NOT_FOUND

    MOV TEMP_CART_INDEX,BL

    MOV AL,TEMP_BOOK_ID
    CALL FIND_BOOK_INDEX
    MOV TEMP_BOOK_INDEX,BL

CHANGE_CART_QUANTITY_INPUT:
    PRINT_STRING NEW_QUANTITY_INPUT
    INPUT_INT
    SUB AL,48
    MOV TEMP_QUANTITY,AL
    NEW_LINE

    MOV AL,TEMP_QUANTITY
    CMP AL,1
    JB CHANGE_INVALID_QUANTITY
    CMP AL,9
    JA CHANGE_INVALID_QUANTITY
    JMP CHANGE_QTY_OK

CHANGE_INVALID_QUANTITY:
    PRINT_STRING INVALID_QUANTITY
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP CHANGE_CART_QUANTITY_INPUT

CHANGE_QTY_OK:

    MOV BL,TEMP_BOOK_INDEX
    MOV BH,0

    CMP AL,BOOK_STOCK[BX]
    JA CHANGE_NOT_ENOUGH

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX

    MOV AL,TEMP_QUANTITY
    MOV CART_QUANTITY[SI],AL

    PRINT_STRING QUANTITY_CHANGED
    NEW_LINE
    JMP CHANGE_DONE

CHANGE_NOT_ENOUGH:
    PRINT_STRING NOT_ENOUGH_STOCK
    NEW_LINE
    JMP CHANGE_DONE

CHANGE_EMPTY:
    PRINT_STRING CART_EMPTY
    NEW_LINE
    JMP CHANGE_DONE

CHANGE_NOT_FOUND:
    PRINT_STRING BOOK_NOT_IN_CART
    NEW_LINE

CHANGE_DONE:
    CALL WAIT_FOR_ZERO
    RET

CHANGE_CART_QUANTITY ENDP


; ---------------- VIEW CART ----------------

VIEW_CART PROC

    CLEAR_SCREEN
    PAGE_TITLE CART_MENU_TITLE

    CMP CART_COUNT,0
    JE VIEW_CART_EMPTY

    MOV SI,0

VIEW_CART_LOOP:

    MOV AX,0
    MOV AL,CART_COUNT
    CMP SI,AX
    JAE VIEW_CART_DONE

    MOV AX,SI
    MOV TEMP_CART_INDEX,AL

    PRINT_STRING SPACED_DASHES
    NEW_LINE

    PRINT_STRING CART_BOOK
    MOV AL,CART_BOOK_IDS[SI]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING CART_TITLE
    MOV AL,CART_BOOK_IDS[SI]
    CALL PRINT_BOOK_TITLE
    NEW_LINE

    PRINT_STRING CART_QTY
    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV DI,AX
    MOV AL,CART_QUANTITY[DI]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING CART_PRICE

    MOV AL,CART_BOOK_IDS[SI]
    CALL FIND_BOOK_INDEX

    MOV AL,TEMP_BOOK_INDEX
    MOV AH,0
    MOV BX,AX

    MOV AL,BOOK_PRICES[BX]
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX
    INC SI
    JMP VIEW_CART_LOOP

VIEW_CART_EMPTY:
    PRINT_STRING CART_EMPTY
    NEW_LINE

VIEW_CART_DONE:
    CALL WAIT_FOR_ZERO
    RET

VIEW_CART ENDP


; ---------------- PRINT BOOK TITLE ----------------

PRINT_BOOK_TITLE PROC

    CMP AL,1
    JE PRINT_TITLE_1

    CMP AL,2
    JE PRINT_TITLE_2

    CMP AL,3
    JE PRINT_TITLE_3

    CMP AL,4
    JE PRINT_TITLE_4

    CMP AL,5
    JE PRINT_TITLE_5

    RET

PRINT_TITLE_1:
    PRINT_STRING BOOK1_TITLE
    RET

PRINT_TITLE_2:
    PRINT_STRING BOOK2_TITLE
    RET

PRINT_TITLE_3:
    PRINT_STRING BOOK3_TITLE
    RET

PRINT_TITLE_4:
    PRINT_STRING BOOK4_TITLE
    RET

PRINT_TITLE_5:
    PRINT_STRING BOOK5_TITLE
    RET

PRINT_BOOK_TITLE ENDP


; ---------------- AUTOMATIC BILL ----------------

GENERATE_BILL PROC

    CLEAR_SCREEN
    PAGE_TITLE BILL_TITLE

    CMP CART_COUNT,0
    JE BILL_EMPTY

    MOV SUBTOTAL,0
    MOV TOTAL_ITEMS,0
    MOV SI,0

BILL_LOOP:

    MOV AX,0
    MOV AL,CART_COUNT
    CMP SI,AX
    JAE BILL_CALCULATED

    MOV AX,SI
    MOV TEMP_CART_INDEX,AL

    MOV AL,CART_BOOK_IDS[SI]
    CALL FIND_BOOK_INDEX
    MOV TEMP_BOOK_INDEX,BL

    MOV AL,TEMP_BOOK_INDEX
    MOV AH,0
    MOV BX,AX

    MOV AL,BOOK_PRICES[BX]
    MOV AH,0
    MOV DI,AX

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX

    MOV BL,CART_QUANTITY[SI]
    MOV BH,0

    MOV AX,DI
    MUL BX
    ADD SUBTOTAL,AX

    MOV AL,CART_QUANTITY[SI]
    ADD TOTAL_ITEMS,AL

    MOV AL,TEMP_CART_INDEX
    MOV AH,0
    MOV SI,AX
    INC SI

    JMP BILL_LOOP


BILL_CALCULATED:

    MOV DISCOUNT,0

    CMP CURRENT_BRACU,1
    JNE BILL_NO_DISCOUNT

    CMP TOTAL_ITEMS,3
    JAE BILL_APPLY_DISCOUNT
    JMP BILL_NO_DISCOUNT


BILL_APPLY_DISCOUNT:

    MOV AX,SUBTOTAL
    MOV DX,0
    MOV BX,5
    DIV BX
    MOV DISCOUNT,AX


BILL_NO_DISCOUNT:

    MOV AX,SUBTOTAL
    SUB AX,DISCOUNT
    MOV FINAL_TOTAL,AX

    PRINT_STRING TOTAL_ITEM_MESSAGE
    MOV AL,TOTAL_ITEMS
    MOV AH,0
    CALL PRINT_NUMBER
    NEW_LINE
    NEW_LINE

    PRINT_STRING BILL_SUBTOTAL
    MOV AX,SUBTOTAL
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING BILL_DISCOUNT
    MOV AX,DISCOUNT
    CALL PRINT_NUMBER
    NEW_LINE

    PRINT_STRING BILL_FINAL
    MOV AX,FINAL_TOTAL
    CALL PRINT_NUMBER
    NEW_LINE
    NEW_LINE

    CMP DISCOUNT,0
    JE BILL_NO_DISCOUNT_MESSAGE

    PRINT_STRING DISCOUNT_APPLIED
    NEW_LINE
    JMP BILL_MESSAGE_DONE


BILL_NO_DISCOUNT_MESSAGE:

    PRINT_STRING NO_DISCOUNT
    NEW_LINE


BILL_MESSAGE_DONE:

    NEW_LINE
    PRINT_STRING BILL_READY
    NEW_LINE
    CALL WAIT_FOR_ZERO
    RET


BILL_EMPTY:

    PRINT_STRING CART_EMPTY
    NEW_LINE
    CALL WAIT_FOR_ZERO
    RET

GENERATE_BILL ENDP


; ---------------- WAIT FOR ZERO ----------------
; Only 0 is accepted for going back.

WAIT_FOR_ZERO PROC

WAIT_ZERO_INPUT:
    PRINT_STRING PRESS_BACK
    NEW_LINE
    INPUT_INT
    CMP AL,'0'
    JE WAIT_ZERO_DONE
    
    NEW_LINE
    PRINT_STRING INVALID_INPUT
    NEW_LINE
    PRINT_STRING GIVE_INPUT_AGAIN
    NEW_LINE
    JMP WAIT_ZERO_INPUT

WAIT_ZERO_DONE:
    RET

WAIT_FOR_ZERO ENDP


; ---------------- PRINT MULTI-DIGIT NUMBER ----------------
; Input: AX = number

PRINT_NUMBER PROC

    CMP AX,0
    JNE PRINT_NUMBER_START

    MOV DL,'0'
    MOV AH,2
    INT 21H
    RET

PRINT_NUMBER_START:

    MOV BX,10
    MOV CX,0

PRINT_NUMBER_DIVIDE:

    MOV DX,0
    DIV BX

    PUSH DX
    INC CX

    CMP AX,0
    JNE PRINT_NUMBER_DIVIDE

PRINT_NUMBER_OUTPUT:

    POP DX
    ADD DL,48

    MOV AH,2
    INT 21H

    LOOP PRINT_NUMBER_OUTPUT

    RET

PRINT_NUMBER ENDP


    END MAIN
